pipeline {
    agent any
    tools {
      maven 'mymaven'
    }
    stages {
        stage ('Build') {
            steps {
                sh "mvn clean package"
            }
        }
        stage ('Deploy') {
            steps {
        sshagent(['Jentomcat']) {
     sh "scp -o StrictHostKeyChecking=no target/*.war ansadmin@44.200.240.212:/home/ansadmin/tomcat/webapps"
}
         }
       }
    }
}
